### PR TITLE
Added Alert and Button components

### PR DESCRIPTION
**Pull request by ravikumar0403**
Added new components to the library. The alert and button component has four variants
- Primary 
- Success 
- Warning 
- Danger

### CODE REVIEW

**Review by yashpatel1797 — COMMENTED** [review]
All code looks good to me. UI is clean and colours choice is also good.

**Comment by poojavishnoi** [comment]
Cool..Code is also clean. Great work!

**Comment by parthpandyappp** [comment]
I've started a review. Just get it done (I feel you should). Rather you're good to go. Pleasant colors, Clean UI and code. Rest LGTM :+1:

**Review by shashikantmaurya0007 — APPROVED** [review]
UI looks good :)

**Pull request merged**
